# Generated by Django 4.0.1 on 2022-01-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default=1000000, null=True),
        ),
    ]
