# Generated by Django 4.0.1 on 2022-02-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
