# Generated by Django 4.0.1 on 2022-01-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
