# Generated by Django 4.0.1 on 2022-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_avatar_alter_address_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.CharField(blank=True, choices=[('Bestseller', 'Bestseller'), ('Last items', 'Last items')], default='Different', max_length=100, null=True),
        ),
    ]
