# Generated by Django 4.0.1 on 2022-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='inpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
