# Generated by Django 4.0.1 on 2022-01-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_courier_product_home_product_inpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='home',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inpost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='post',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.BooleanField(default=False)),
                ('inpost', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
