# Generated by Django 4.0.1 on 2022-02-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_status_product_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='outlet',
            field=models.CharField(blank=True, choices=[('Bestseller', 'Bestseller'), ('Last items', 'Last items')], max_length=100, null=True),
        ),
    ]
