# Generated by Django 4.0.1 on 2022-01-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_courier_remove_product_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.BooleanField(default=False)),
                ('inpost', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='shipment',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
