# Generated by Django 4.0.1 on 2022-01-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_shipment_user_addres_delete_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='purchased_by',
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
