# Generated by Django 4.0.1 on 2022-01-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_shipment_purchased_by_shipment_ship_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ship_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
