# Generated by Django 4.0.1 on 2022-01-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_shipment_ship_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
