# Generated by Django 4.0.1 on 2022-01-24 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_shipment_product_alter_shipment_ship_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
