# Generated by Django 4.0.1 on 2022-01-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_shipment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
