# Generated by Django 4.0.1 on 2022-01-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_ticket_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created',
        ),
    ]
