# Generated by Django 4.0.1 on 2022-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_ticket_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=20)),
                ('contact', models.IntegerField(null=True)),
                ('products', models.ManyToManyField(blank=True, to='base.Product')),
            ],
        ),
    ]
