# Generated by Django 4.0.1 on 2022-01-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='home',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='inpost',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='post',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=False)),
                ('courier', models.BooleanField(default=False)),
                ('inpost', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.delivery'),
        ),
    ]
