# Generated by Django 4.0.1 on 2022-01-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_store_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
    ]
