# Generated by Django 4.0.1 on 2022-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='home',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='inpost',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='post',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='store',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
