# Generated by Django 4.0.1 on 2022-01-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_delivery_courier_remove_delivery_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
