# Generated by Django 4.0.1 on 2022-01-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_delivery_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='store',
        ),
        migrations.AddField(
            model_name='shipment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
