# Generated by Django 4.0.1 on 2022-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_shipment_finished_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Proccesed'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='processed', max_length=30),
        ),
    ]
