# Generated by Django 4.0.1 on 2022-02-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, choices=[('Processed', 'Proccesed'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='processed', max_length=30, null=True),
        ),
    ]
