# Generated by Django 4.0.1 on 2022-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.AddField(
            model_name='shipment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
