# Generated by Django 4.0.1 on 2022-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_remove_shipment_store_delivery_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Inpost', 'Inpost'), ('Courier', 'Courier'), ('Local Store - Carrefour Zielona Gora', 'Local Store ZG'), ('Local Store - Vaticano', 'Local Store JP2GMD')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
