# Generated by Django 4.0.1 on 2022-02-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_order_orderitem_remove_shipment_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
