# Generated by Django 4.0.1 on 2022-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_product_options_remove_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Different', 'Different'), ('Samsung', 'Samsung'), ('Iphone', 'Iphone'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei')], default='Different', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
