# Generated by Django 4.0.1 on 2022-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_pruce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
