# Generated by Django 4.0.1 on 2022-02-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_product_discount_pruce_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_pruce',
            new_name='discount_price',
        ),
    ]
