# Generated by Django 4.0.1 on 2022-02-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
