# Generated by Django 4.0.1 on 2022-02-10 20:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_ticket_order_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='pobrane.png', force_format=None, keep_meta=True, quality=75, size=[100, 300], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='pobrane.png', force_format=None, keep_meta=True, quality=75, size=[500, 300], upload_to='whatever'),
        ),
    ]
