# Generated by Django 4.0.1 on 2022-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.CharField(default='Zielona Gora', max_length=30),
            preserve_default=False,
        ),
    ]
