# Generated by Django 4.0.1 on 2022-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_rename_address_store_city_store_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='map_addres',
            field=models.URLField(blank=True, null=True),
        ),
    ]
