# Generated by Django 4.0.1 on 2022-02-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_store_map_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='map_addres',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
