# Generated by Django 4.0.1 on 2022-02-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_remove_store_map_addres_store_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(max_length=20)),
                ('body', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='map',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product',
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
