# Generated by Django 4.0.1 on 2022-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_message_created_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
