# Generated by Django 4.0.1 on 2022-02-14 22:26

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_remove_message_receiver_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['subject']),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
