# Generated by Django 4.0.1 on 2022-02-15 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_product_status_shipmentaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereceiver',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messagereceiver',
            name='receiver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
