# Generated by Django 4.0.1 on 2022-02-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_remove_messagereceiver_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereceiver',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messagereceiver',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
