# Generated by Django 4.0.1 on 2022-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_remove_messagereceiver_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
